---
- name: Install Blackfire dependency is installed
  package:
    name: yum-utils
    state: present

- name: Ensure extra Blackfire dependency on older EL versions is installed
  package:
    name: pygpgme
    state: present
  when: ansible_distribution_major_version | int < 8

- name: Install packagecloud GPG key
  rpm_key:
    key: https://packagecloud.io/gpg.key
    state: present

- name: Install Blackfire repository
  get_url:
    url: http://packages.blackfire.io/fedora/blackfire.repo
    dest: /etc/yum.repos.d/blackfire.repo
    mode: 0644

- name: Enforce repo_gpgcheck for blackfire repository
  lineinfile:
    dest: /etc/yum.repos.d/blackfire.repo
    regexp: "^repo_gpgcheck="
    line: "repo_gpgcheck={{ '0' if blackfire_disable_repo_gpgcheck else '1' }}"
    state: present

- name: Install Blackfire packages
  package:
    name:
      - blackfire-agent
      - blackfire-php
    state: present
  notify:
    - restart php-fpm
